var globalModelsDetails = {
    "a80": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Supra A80"
    },
	"a90": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 260,
        priv: "Полный привод",
        mass: "1.480 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Supra A90"
    },
	"bmwe28": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 120,
        priv: "Задний привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW E28"
    },
	"bmwe34": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "2.625 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW E34"
    },
	"bmwe36": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 328,
        priv: "Задний привод",
        mass: "1.356 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW E36"
    },
	"bmwe38": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 326,
        priv: "Задний привод",
        mass: "1.368 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW E38"
    },
	"bmwe39": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 285,
        priv: "Задний привод",
        mass: "1.385 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW E39"
    },
	"bmwe46": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 330,
        priv: "Полный привод",
        mass: "1.600 кг.",
        vnet: "Нет", 
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW E46"
    },
	"a45": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Полный привод",
        mass: "1.750 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz A45"
    },
	"gta5rp_veh_cam08": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 420,
        priv: "Задний привод",
        mass: "1.395 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Camry 40"
    },
	"camry70": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 318,
        priv: "Задний привод",
        mass: "1.650 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Camry 55"
    },
	"amggt16": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Передний привод",
        mass: "1.163 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz AMG GT16"
    },
	"bmw730": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 306,
        priv: "Полный привод",
        mass: "2.491 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW 730"
    },
	"bmwg05": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.930 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW G05"
    },
	"cayen19": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Задний привод",
        mass: "1.550 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche Cayenne 2019"
    },
	"bmwm2": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 333,
        priv: "Полный привод",
        mass: "2.244 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M2"
    },
	"2019m5": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "3.700 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5"
    },
	"18rs7": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 380,
        priv: "Полный привод",
        mass: "1.975 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS7"
    },
	"g63": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 306,
        priv: "Задний привод",
        mass: "1.527 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz G63"
    },
	"gta5rp_veh_c63s": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Задний привод",
        mass: "1.725 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz C63s"
    },
	"carrera19": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 290,
        priv: "Задний привод",
        mass: "1.680 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche 911 Carrera"
    },
	"c63scoupe": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Передний привод",
        mass: "1.690 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz C63s Coupe"
    },
	"bentayga": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 286,
        priv: "Полный привод",
        mass: "2.175 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bentley Bentayga"
    },
	"bentley20": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 420,
        priv: "Полный привод",
        mass: "2.625 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bentley Continental"
    },
	"mc720s": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.660 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren 720S"
    },
	"p1lm": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 335,
        priv: "Задний привод",
        mass: "1.941 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren P1 LM"
    },
	"cyber": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.650 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Tesla Syber Track"
    },
	"silvias15": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.825 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan Silvia S-15"
    },
	"nisgtr": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.940 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan GT-R 35"
    },
	"skyline": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.800 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan Skyline GT-R 34"
    },
	"zondac": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 230,
        priv: "Полный привод",
        mass: "1.862 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Pagani Zonda R"
    },
	"sianr": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 340,
        priv: "Задний привод",
        mass: "1.435 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Sian"
    },
	"asvj": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.485 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Aventador SVJ"
    },
	"chiron": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 312,
        priv: "Задний привод",
        mass: "1.735 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bugatti Chiron"
    },
	"veneno": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.107 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Veneno"
    },
	"supersport": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 230,
        priv: "Полный привод",
        mass: "2.580 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Buggati Veyron SUPER-Sport"
    },
	"divo": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.350 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bugatti Divo"
    },
	"sr650fly": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.580 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Яхта SR-650fly"
    },
	"m3f80": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 182,
        priv: "Задний привод",
        mass: "1.577 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M3 f80"
    },
	"m5e60": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 175,
        priv: "Передний привод",
        mass: "1.160 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5 e60"
    },
	"m6f13": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Передний привод",
        mass: "1.060 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M6 f13"
    },
	"x5e53": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 204,
        priv: "Задний привод",
        mass: "1.044 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X5 e53"
    },
	"x5m2016": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 197,
        priv: "Задний привод",
        mass: "1.250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X5M 2016"
    },
	"x5me70": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Задний привод",
        mass: "1.250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X5M e70"
    },
	"x6m": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 225,
        priv: "Полный привод",
        mass: "1.370 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X6M"
    },
	"z3m": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "1.495 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW Z3M"
    },
	"demonhawk": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 221,
        priv: "Полный привод",
        mass: "1.253 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Jeep DEMONHAWK"
    },
	"srt8b": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Передний привод",
        mass: "970 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Dodge Challenger SRT-8"
    },
	"rt70": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 272,
        priv: "Передний привод",
        mass: "1.470 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Dodge RT 70"
    },
	"evo9": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.960 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mitsubishi Lancer Evolution IX"
    },
	"evo10": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 260,
        priv: "Задний привод",
        mass: "1.250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mitsubishi Lancer Evolution X"
    },
	"f458": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Задний привод",
        mass: "1.255 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ferrari 458"
    },
	"focusrs": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 242,
        priv: "Полный привод",
        mass: "1.590 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Focus RS"
    },
	"shelbygt500": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.540 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Mustang ShelbyGT"
    },
	"gdaq50": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 195,
        priv: "Полный привод",
        mass: "2.585 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Infinity Q50"
    },
	"lx2018": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 240,
        priv: "Задний привод",
        mass: "1.543 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lexus LX 2018"
    },
	"exige12": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 270,
        priv: "Задний привод",
        mass: "2.010 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lotus Exige12"
    },
	"trans69": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Полный привод",
        mass: "1.340 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "trans69"
    },
	"pgt3": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Полный привод",
        mass: "2.585 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "pgt3"
    },
	"m3e46": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.570 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M3 e46"
    },
	"m4f82": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Задний привод",
        mass: "1.570 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M4 f82"
    },
	"mlbrabus": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.130 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes ML Brabus"
    },
	"mustangbkit": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 289,
        priv: "Задний привод",
        mass: "1.707 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Mustang"
    },
	"navigator": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.656 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lincoln Navigator"
    },
	"nismo20": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 320,
        priv: "Полный привод",
        mass: "1.650 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan GTR Nismo"
    },
	"ody18": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 190,
        priv: "Передний привод",
        mass: "1.760 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Honda Odyssey"
    },
	"p1": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Задний привод",
        mass: "1.490 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren P1"
    },
	"panamera17turbo": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 306,
        priv: "Полный привод",
        mass: "1.995 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche Panamera Turbo"
    },
	"passat": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 232,
        priv: "Передний привод",
        mass: "1.480 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volkswagen Passat"
    },
	"q820": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 232,
        priv: "Полный привод",
        mass: "2.220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi Q8"
    },
	"r820": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 331,
        priv: "Полный привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi R8"
    },
	"rmodf12tdf": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 340,
        priv: "Задний привод",
        mass: "1.520 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ferrari F12 TDF"
    },
	"rr12": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 225,
        priv: "Полный привод",
        mass: "2.710 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Range Rover Supercharged"
    },
	"rs5r": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Полный привод",
        mass: "1.840 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS5"
    },
	"rs7r": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 305,
        priv: "Полный привод",
        mass: "2.065 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS7"
    },
		"rmodrs6": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 305,
        priv: "Полный привод",
        mass: "2.075 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS6"
    },
		"rs318": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.585 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS3"
    },
		"skyline": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.550 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan Skyline GTR R34"
    },
		"slsamg": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 317,
        priv: "Задний привод",
        mass: "1.695 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz SLS Amg"
    },
		"sq72016": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.345 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi SQ7"
    },
		"rmodjeep": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 258,
        priv: "Полный привод",
        mass: "2.418 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Jeep Trackhawk"
    },
		"sti": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.480 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Subaru Impreza WRX STI"
    },
		"superb": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 240,
        priv: "Передний привод",
        mass: "1.535 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Skoda Superb"
    },
		"a80": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.500 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Supra"
    },
		"asvj": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Полный привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Aventador SVJ"
    },
		"tahoe": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 192,
        priv: "Полный привод",
        mass: "2.291 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Chevrolet Tahoe"
    },
		"teslapd": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 260,
        priv: "Полный привод",
        mass: "2.263 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Tesla Model S"
    },
		"teslax": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 260,
        priv: "Полный привод",
        mass: "2.509 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Tesla Model X"
    },
		"uaz3159": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "UAZ"
    },
		"urban": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 137,
        priv: "Полный привод",
        mass: "1.425 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Niva Urban"
    },
		"urus": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 305,
        priv: "Полный привод",
        mass: "2.200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Urus"
    },
		"v250": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 206,
        priv: "Полный привод",
        mass: "2.105 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz V250"
    },
		"velar": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 274,
        priv: "Полный привод",
        mass: "2.160 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Range Rover Velar"
    },
		"veneno": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 355,
        priv: "Полный привод",
        mass: "1.540 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Veneno"
    },
		"viper": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.521 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Dodge Viper"
    },
		"vwtouareg": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 245,
        priv: "Полный привод",
        mass: "2.150 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volkswagen Touareg"
    },
		"s600w220": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "2.190 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes Benz S600 w220"
    },
		"rrw13": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "2.435 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Rolls-Royce Wraith Black Badge"
    },
		"cls2015": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 300,
        priv: "Полный привод",
        mass: "1.870 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes Benz CLS63 AMG"
    },
		"ram1500": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 200,
        priv: "Полный привод",
        mass: "2.435 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Dodge Ram"
    },
		"x5e53": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 246,
        priv: "Полный привод",
        mass: "2.275 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X5 e53"
    },
		"x5g05": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.350 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X5 30D"
    },
		"x7bmw": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.555 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X7"
    },
		"xc60": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 210,
        priv: "Полный привод",
        mass: "1.990 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volvo XC60"
    },
		"z4bmw": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.610 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW Z4"
    },
		"rmodcamaro": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 316,
        priv: "Задний привод",
        mass: "1.761 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Chevrolet Camaro ZL1"
    },
	"lamboreventon": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 358,
        priv: "Полный привод",
        mass: "1.666 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Reventon"
    },
	    "Bmx": {
        desc: "",
        seats: 1,
        acceleration: 0.265,
        maxSpeed: 50,
        priv: "Задний привод",
        mass: "25 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMX"
    },
	"akuma": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 145,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Akuma"
    },
	"Double": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 147,
        priv: "Задний привод",
        mass: "200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Double"
    },
	"Enduro": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 119,
        priv: "Задний привод",
        mass: "220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Enduro"
    },
	"Thrust": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 152,
        priv: "Задний привод",
        mass: "270 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Thrust"
    },
	"Vindicator": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 148,
        priv: "Задний привод",
        mass: "280 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Vindicator"
    },
	"Hexer": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 135,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Hexer"
    },
	"Sanchez2": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 118,
        priv: "Задний привод",
        mass: "220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Sanchez"
    },
	"CarbonRS": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 145,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Carbon RS"
    },
	"Bati": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Задний привод",
        mass: "230 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bati"
    },
	"Faggio2": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 90,
        priv: "Задний привод",
        mass: "100 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Faggio"
    },
	"Ruffian": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ruffian"
    },
	"Lectro": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lectro"
    },
	"Nemesis": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nemesis"
    },
	"Hakuchou": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Hakuchou"
    },
	"PCJ": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 130,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "PCJ"
    },
	"Blazer": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 120,
        priv: "Задний привод",
        mass: "600 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Blazer"
    },
	"Diablous": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 142,
        priv: "Задний привод",
        mass: "220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Diablous"
    },
	"Cliffhanger": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Задний привод",
        mass: "220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Cliffhanger"
    },
	"Nightblade": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 142,
        priv: "Задний привод",
        mass: "205 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nightblade"
    },
	"Gargoyle": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 143,
        priv: "Задний привод",
        mass: "210 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Gargoyle"
    },
	"Ratbike": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 130,
        priv: "Задний привод",
        mass: "180 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ratbike"
    },
	"BF400": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 141,
        priv: "Задний привод",
        mass: "200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BF400"
    },
	"verus": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 131,
        priv: "Задний привод",
        mass: "200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Verus"
    },
	"Sanctus": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 144,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Sanctus"
    },
	"Scorcher": {
        desc: "",
        seats: 1,
        acceleration: 0.265,
        maxSpeed: 55,
        priv: "Задний привод",
        mass: "40 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Scorcher"
    },
	"16charger": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 270,
        priv: "Задний привод",
        mass: "1.845 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Dodge Charger Demon 2019"
    },
"fleet78": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 200,
        priv: "Задний привод",
        mass: "1.960 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Cadillac Fleetwood"
    },
"812nlargo": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ferrari 812 Nlargo"
    },
	"italirsx": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "1.730 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Grotti ItaliRSX"
    },
"fairlane66": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 206,
        priv: "Задний привод",
        mass: "1.600 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Fairlane"
    },
	"evo9": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.465 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mitsubishi Evo 9"
    },
	"j50": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 335,
        priv: "Задний привод",
        mass: "1.544 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ferrari J50"
    },
	"722s": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 334,
        priv: "Задний привод",
        mass: "1.940 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes Benz SLR McLaren"
    },
	"mlnovitec": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Полный привод",
        mass: "2.200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Maserati Lavente Novitec"
    },
	"ghost": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "2.360 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Rolls Royce Ghost"
    },
	"mig": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 348,
        priv: "Задний привод",
        mass: "1.365 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ferrari Enzo"
    },
	"senna": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 335,
        priv: "Задний привод",
        mass: "2.360 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren Senna"
    },
	"17m760i": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.755 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW 760i"
    },
	"19dbs": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 342,
        priv: "Задний привод",
        mass: "1.799 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Aston Martin DBS"
    },
	"vantage": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 314,
        priv: "Задний привод",
        mass: "1.530 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Aston Martin Vantage"
    },
	"ast": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 324,
        priv: "Задний привод",
        mass: "1.739 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Aston Martin Vanquish"
    },
	"db11": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 334,
        priv: "Задний привод",
        mass: "1.765 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Aston Martin DB11"
    },
	"aventadorishe": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Полный привод",
        mass: "1.575 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Aventador ONYX"
    },
"lp610": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Полный привод",
        mass: "1.422 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Huracan Coupe"
    },
"760m": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 330,
        priv: "Полный привод",
        mass: "1.810 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M760 Manhart"
    },
"s15mak": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 244,
        priv: "Задний привод",
        mass: "1.250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan Silvia"
    },
"ls430": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.840 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lexus LS430"
    },	
"2019m5": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 305,
        priv: "Полный привод",
        mass: "1.865 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5f90 Competition"
    },
"rmodsianr": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Полный привод",
        mass: "1.622 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Sian Roadster"
    },	
"g20wide": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 240,
        priv: "Задний привод",
        mass: "1.530 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW G20 320d"
    },
	"vulcan": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 360,
        priv: "Задний привод",
        mass: "1.350 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Aston Martin Vulcan"
    },
"bg700w": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "2.485 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "G63 Brabus 700"
    },	
"fpacehm": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.851 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Jaguar F-pace Hamann"
    },	
"sultan": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "1.400 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Sultan"
    },	
"sultanrs": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "1.400 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Sultan RS"
    },		
"kuruma": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "1.851 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Kuruma"
    },		
"focusrs": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Полный привод",
        mass: "1.851 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Focus RS"
    },		
"m3e92": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.655 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M3 E92"
    },
	
"boxville4": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "35000",
        vnut: "Да",
        rn: "Boxville"
    },
"e15082": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "10000",
        vnut: "Да",
        rn: "Ford E-150 Van 1982"
    },	
"nspeedo": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "75000",
        vnut: "Да",
        rn: "Vapid Speedo Express"
    },	
"mule3": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "100000",
        vnut: "Да",
        rn: "Mule 3"
    },	
"mule4": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "130000",
        vnut: "Да",
        rn: "Mule 4"
    },	
"pounder2": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "250000",
        vnut: "Да",
        rn: "Pounder"
    },	
"c63w205": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 290,
        priv: "Задний привод",
        mass: "1.655 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Нет",
        rn: "Mercedes-Benz AMG C63s"
    }, 
"sprinter211": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Задний привод",
        mass: "2.140 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "170000",
        rn: "Mercedes-Benz Sprinter"
    },
	"buzzard2": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Buzzard"
    },
	"frogger": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Frogger"
    },
	"frogger2": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Frogger 2"
    },
	"havok": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Havok"
    },
	"maverick": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Maverick"
    },
	"seasparrow": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Seasparrow"
    },
	"supervolito": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Supervolito"
    },
	"supervolito2": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Supervolito 2"
    },
	"swift": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Swift"
    },
	"swift2": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Swift 2"
    },
	"volatus": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volatus"
    },
	"seasparrow2": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Seasparrow"
    },
	"microlight": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Microlight"
    },
	"howard": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Howard"
    },
	"snowmobile": {
        desc: "",
        seats: 1,
        acceleration: 0.265,
        maxSpeed: 115,
        priv: "Полный привод",
        mass: "450 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "SnowMoto"
    },
	"alpinab7": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 329,
        priv: "Полный привод",
        mass: "2.070 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "BMW Alpina B7 2020"
    },
	"lp700dmc": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Задний привод",
        mass: "1.575 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "Ferrari 812 N-largo"
    },
	"rs6m": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 320,
        priv: "Передний привод",
        mass: "2.100 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "Audi RS6 Mansory Sedan"
    },
	"xc90": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Полный привод",
        mass: "1.939 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "Volvo XC90"
    },
};